server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server-parcial
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cjmm0811/parcial_Backend2_CristianMendieta.git
          default-label: main
          force-pull: true
          search-paths: configuration-exam



